name: build

on:
  push:
    branches:
      - 'master'
  schedule:
    # everyday 11AM (UTC)
    - cron: '* 9 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache bundle directory
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Setup build env
        run: |
          git submodule init
          git submodule update
          sudo apt-get install ruby-dev po4a
          sudo gem install bundler
      - name: Exec po4a-translate
        run: bin/exec-po4a-translate
      - name: Exec jekyll
        run: bin/exec-jekyll
      - name: Configure git
        run: |
          git config --local user.email "mail@ynojima.net"
          git config --local user.name "ynojima"
      - name: Commit & Push
        run: |
          git checkout -b gh-pages
          git add --force docs
          git commit -m "Deploy i18n-quarkusio"
          git push -f origin gh-pages
