name: build

on:
  push:
    branches:
      - 'master'
  schedule:
    # everyday 11AM (UTC)
    - cron: '* 9 * * *'
  workflow_dispatch:
    branches:
      - 'master'
  workflow_run:
    workflows:
      - 'sync-upstream'
    branches:
      - 'master'
    types:
      - completed

jobs:
  build-tmx:
    name: Build tmx
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache bundle directory
        uses: actions/cache@v1
        with:
          path: vendor/bundleb
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Configure git
        run: |
          git submodule init
          git submodule update
          git config --local user.email "mail@ynojima.net"
          git config --local user.name "ynojima"
      - name: Setup build env
        run: |
          sudo apt-get install ruby-dev po4a
          sudo gem install bundler
          sudo npm --global install surge
          sudo pip3 install translate-toolkit
      - name: Build tmx
        run: bin/build-tmx

  deploy-ja:
    name: Deploy Japanese translation to surge.sh
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache bundle directory
        uses: actions/cache@v1
        with:
          path: vendor/bundleb
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Configure git
        run: |
          git submodule init
          git submodule update
          git config --local user.email "mail@ynojima.net"
          git config --local user.name "ynojima"
      - name: Setup build env
        run: |
          sudo apt-get install ruby-dev po4a
          sudo gem install bundler
          sudo npm --global install surge
      - name: Exec po4a-translate
        run: bin/exec-po4a-translate
      - name: Apply override files
        run: bin/exec-override
      - name: Exec jekyll
        run: bin/exec-jekyll
      - name: Deploy to surge.sh
        run: |
          surge docs ja-i18n-quarkusio.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
