name: pull-request

on: pull_request

jobs:
  deploy-ja:
    name: Deploy Japanese translation to surge.sh
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache bundle directory
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Setup build env
        run: |
          git submodule init
          git submodule update
          sudo apt-get install ruby-dev po4a
          sudo gem install bundler
          sudo npm --global install surge
      - name: Exec po4a-translate
        run: bin/exec-po4a-translate
      - name: Apply override files
        run: bin/exec-override
      - name: Exec jekyll
        run: bin/exec-jekyll
      - name: Deploy to surge
        run: |
          surge docs pr-preview-"$GITHUB_RUN_NUMBER"-i18n-quarkusio.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - name: Add comment
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let body = `Site preview(ja): https://pr-preview-${context.runNumber}-ja-i18n-quarkusio.surge.sh`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
