name: pull-request

on: pull_request

jobs:
  deploy-ja:
    name: Deploy Japanese translation to surge.sh
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache bundle directory
        uses: actions/cache@v1
        with:
          path: vendor/bundleb
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Setup build env
        run: |
          bin/setup-build-env
      - name: Configure git
        run: |
          bin/configure-git

      - name: Exec po4a-translate
        run: bin/exec-po4a-translate
      - name: Apply override files
        run: bin/exec-override
      - name: Exec jekyll
        run: bin/exec-jekyll
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/
