name: pull-request

on: pull_request

jobs:
  deploy-ja:
    name: Deploy Japanese translation to surge.sh
    runs-on: ubuntu-20.04
    steps:
      - name: Cache bundle directory
        uses: actions/cache@v1
        with:
          path: vendor/bundleb
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Setup build env
        run: |
          sudo apt-get update
          sudo apt-get -y install po4a python3-pip git ruby-dev po4a nodejs npm
          sudo pip3 install translate-toolkit
          sudo gem install bundler
          sudo npm --global install surge
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          bin/configure-git

      - name: Exec po4a-translate
        run: bin/exec-po4a-translate
      - name: Apply override files
        run: bin/exec-override
      - name: Exec jekyll
        run: bin/exec-jekyll
      - name: Deploy to surge
        run: |
          surge docs pr-preview-"${{ github.event.pull_request.number }}"-ja-i18n-quarkusio.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - name: Add comment
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let body = `Site preview(ja): https://pr-preview-${{ github.event.pull_request.number }}-ja-i18n-quarkusio.surge.sh`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
