name: pull-request-feedback

on:
  workflow_run:
    workflows: ["pull-request"]
    types:
      - completed

jobs:
  deploy-ja:
    name: Deploy Japanese translation to surge.sh
    runs-on: ubuntu-20.04
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var docsArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "docs"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: docsArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/docs.zip', Buffer.from(download.data));
      - name: Setup build env
        run: |
          bin/setup-build-env
      - name: Unzip docs
        run: unzip docs.zip -d docs
      - name: Deploy to surge
        run: |
          surge docs pr-preview-"${{ github.event.pull_request.number }}"-ja-quarkusio.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - name: Add comment
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let body = `Site preview: https://pr-preview-${{ github.event.pull_request.number }}-ja-quarkusio.surge.sh`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
