name: sync upstream

on:
  schedule:
    # every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:
    branches:
      - 'master'

jobs:
  build:
    name: Sync
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup build env
        run: |
          sudo apt-get install po4a
      - name: Configure git
        run: |
          git submodule init
          git submodule update
          git config --local user.email "mail@ynojima.net"
          git config --local user.name "ynojima"
      - name: Sync upstream
        run: bin/sync-upstream
      - name: Exec po4a-updatepo
        run: bin/exec-po4a-updatepo
      - name: Add machine translations
        run: bin/add-machine-translations
        env:
          TRANSLATOR_DEEPL_APIKEY: ${{ secrets.TRANSLATOR_DEEPL_APIKEY }}
      - name: Trigger build workflow
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build.yml",
              ref: "master"
            })
