name: sync upstream

on:
  schedule:
    # everyday 11AM (UTC)
    - cron: '* 9 * * *'

jobs:
  build:
    name: Sync
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
