name: sync upstream

on:
  schedule:
    # every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  build:
    name: Sync
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git submodule init
          git submodule update
          git config --local user.email "mail@ynojima.net"
          git config --local user.name "ynojima"
      - name: Commit & Push
        run: bin/sync-upstream